'use client';

import { useState, useEffect } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2, Truck, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';

export default function DeliveryCard({ orderId, orderStatus }: { orderId: string, orderStatus: string }) {
    const supabase = createClient();
    const [assignment, setAssignment] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [requesting, setRequesting] = useState(false);

    useEffect(() => {
        fetchAssignment();
    }, [orderId]);

    const fetchAssignment = async () => {
        try {
            const { data, error } = await supabase
                .from('delivery_assignments')
                .select('*')
                .eq('order_id', orderId)
                .single();

            if (!error && data) {
                setAssignment(data);
            }
        } catch (e) {
            // No assignment found
        } finally {
            setLoading(false);
        }
    };

    const requestDelivery = async () => {
        setRequesting(true);
        try {
            const { data: userData } = await supabase.auth.getUser();
            if (!userData.user) return;

            // Create assignment
            const { data, error } = await supabase
                .from('delivery_assignments')
                .insert({
                    order_id: orderId,
                    status: 'pending',
                    // pickup_otp: Math.floor(1000 + Math.random() * 9000).toString(), // Generated by trigger or backend usually, but for client-side demo:
                    pickup_otp: Math.floor(1000 + Math.random() * 9000).toString(),
                    delivery_otp: Math.floor(1000 + Math.random() * 9000).toString(),
                })
                .select()
                .single();

            if (error) throw error;
            setAssignment(data);
            toast.success('Delivery requested successfully!');
        } catch (error: any) {
            console.error(error);
            toast.error('Failed to request delivery');
        } finally {
            setRequesting(false);
        }
    };

    if (loading) return <div className="h-24 flex items-center justify-center"><Loader2 className="animate-spin" /></div>;

    return (
        <Card className="bg-card border-border">
            <CardHeader>
                <CardTitle className="text-lg flex items-center gap-2">
                    <Truck className="w-5 h-5" />
                    Delivery
                </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
                {assignment ? (
                    <div className="space-y-2">
                        <div className="flex justify-between items-center">
                            <span className="text-sm text-muted-foreground">Status</span>
                            <span className="font-medium uppercase text-blue-600">{assignment.status.replace('_', ' ')}</span>
                        </div>
                        {assignment.status === 'accepted' && (
                            <div className="p-3 bg-muted rounded-md space-y-1">
                                <div className="text-xs text-muted-foreground">Pickup OTP</div>
                                <div className="text-lg font-mono font-bold tracking-widest">{assignment.pickup_otp}</div>
                            </div>
                        )}
                        {assignment.driver_id && (
                            <div className="text-sm text-muted-foreground flex items-center gap-1">
                                <CheckCircle className="w-4 h-4 text-green-500" /> Driver Assigned
                            </div>
                        )}
                    </div>
                ) : (
                    <div className="space-y-3">
                        <p className="text-sm text-muted-foreground">Request a Vallaroo driver to deliver this order.</p>
                        <Button
                            className="w-full"
                            onClick={requestDelivery}
                            disabled={requesting}
                        >
                            {requesting && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                            Request Delivery
                        </Button>
                    </div>
                )}
            </CardContent>
        </Card>
    );
}
